import Head, { defaultHead } from "next/head"
import Navigation from "./navigation"

const Layout = ({ children, title = 'Car Wash' }) => {
    return (
        <div className="bg-gradient-to-r from-emerald-100 to-emerald-900">
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by V.Ganchev" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navigation />
            {children}
        </div>
    )
}

export default Layout